### ISSUE TITLE
How to find the intersection？

### ISSUE THREAD

**Issue by relinda2019** [OldPanda/bloomfilter-py#10]
If I get the bloofilter object of two arrays, how to find the intersection of the two arrays？very thankful！！

**Comment by OldPanda** [comment]
@relinda2019 Thanks for raising the issue. Are you talking about the ["The union and intersection of sets" part](https://en.wikipedia.org/wiki/Bloom_filter#The_union_and_intersection_of_sets) in the wiki page? Unfortunately, the calculation of the intersection size is not supported yet.

**Comment by OldPanda** [comment]
Close this issue due to long time inactivity. Please feel free to reopen or create a new one if you have any questions in future. Thanks!
