### ISSUE TITLE
Byte decoding fails while converting to string.

### ISSUE THREAD

**Issue by engineerpassion** [OldPanda/bloomfilter-py#4]
**Use case:**

- To convert the bloom filter object into a string in order to store and retrieve as and when required.

**Problem:**

- While converting the bytes object after using the `dumps()` method on the bloom filter object into a string via the `decode()` method, it fails (in some cases when typically the integers added to the filter are larger) as below:

    ```
  File ~/.pyenv/versions/3.10.6/lib/python3.10/encodings/utf_8.py:16, in decode(input, errors)
       15 def decode(input, errors='strict'):
  ---> 16     return codecs.utf_8_decode(input, errors, True)
  
  UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 6: invalid start byte
    ```

**Code to reproduce:**

```
import random
from bloomfilter import BloomFilter
bf = BloomFilter(expected_insertions=10, err_rate=0.1)
bf.put(random.randint(100000000, 10000000000))
bf.put(random.randint(100000000, 10000000000))
bf.dumps().decode()
```

**My observations:**

The encoding being used here for serializing the bloom filter to bytes is neither of [`utf-8`, `ascii`, `utf-16`, `utf-32`] as the byte codecs seen are not supported in either of these.

**Probable solutions:**

1. Use the `utf-8` encoding while serializing the bloom filter object.
2. Allow users to specify the encoding to be used.

**Comment by OldPanda** [comment]
Thanks for raising the issue! I'm fairly busy these days and cannot guarantee a fix anytime soon. Would you mind sending a pull request if you have a solution from your side? Thanks!

**Comment by engineerpassion** [comment]
I looked at the code and could not see any obvious solution, but have found a workaround with hex as of now.

Thanks for your attention!

**Comment by OldPanda** [comment]
@engineerpassion I'm glad that you found a workaround to convert it to hex for now.

I reviewed the problem here, but I think you can store the byte array(generated by `bf.dumps()`) somewhere(file or db). It doesn't seem necessary to support converting it to a string. Would you mind sharing the motivations of converting binary to other format of data? So that I can decide if a conversion function is required here. Thanks!

**Comment by engineerpassion** [comment]
@OldPanda We're using ETCD to store and retrieve the bloom filters via a REST call, hence we need it convertible to a string and back.

**Comment by OldPanda** [comment]
Thanks a lot for sharing your use case! Sounds like providing a function to dump it as hex or base64 could be a good idea, and keep the original `dumps()` as is.

**Comment by engineerpassion** [comment]
Sounds good, thanks!

**Comment by OldPanda** [comment]
Added in [release 0.2.0](https://github.com/OldPanda/bloomfilter-py/releases/tag/v0.2.0)
